"""add modules and timetable

Revision ID: 11dc36039020
Revises: 8b2ff8163bf0
Create Date: 2025-12-23 00:31:44.443393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11dc36039020'
down_revision: Union[str, Sequence[str], None] = '8b2ff8163bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    op.create_table('timetable_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_sessions_date'), 'timetable_sessions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_sessions_date'), table_name='timetable_sessions')
    op.drop_table('timetable_sessions')
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
